### ISSUE TITLE
Second dungeon not generated correctly

### ISSUE THREAD

**Issue by Jalsson** [BenPyton/ProceduralDungeon#15]
We modified the plugin to spawn the dungeon to its actor location instead of the world 0,0,0 position

The first dungeon is generated correctly in the right spot but the second one only spawns in the room test collisions, see the picture below. 

![image](https://user-images.githubusercontent.com/48365153/188810950-ea865401-5e93-4df8-9b9a-c8d586838df8.png)

Is there something global code in the plugin that prevents it from creating 2 unique dungeons that exists at the same time?

Thank you for help!

**Comment by BenPyton** [comment]
Hello Jalsson,

I don't understand correctly what is your issue...

You are generating 2 dungeons ? Do you have 2 different DungeonGenerator actors in your master scene ?
If so, your issue is that it doesn't generate the second one?

To be honest, I've never tested this situation...

Also you said you have modified the plugin, can you show me the code you've changed if possible?

I didn't undertstand what you want to mean by "only spawns in the room test collision"...
What is this room?
So, the second dungeon is spawning correctly but not in the right location?

Best regards.

**Comment by Jalsson** [comment]
Hello BenPyton, sorry for short initial post I will answer all your questions:

**Changes in Room.cpp**

We changed the initial location in Room.cpp (line 34) to take in position as parameter instead of 0,0,0

`void URoom::Init(URoomData* Data)`
`{`
	`RoomData = Data;`
	`Instance = nullptr;`
	`Position = FIntVector(0,0,0);`

<hr>

`void URoom::Init(URoomData* Data, FIntVector position)`
`{`
	`RoomData = Data;`
	`Instance = nullptr;`
	`Position = position;`
	`Direction = EDoorDirection::North;`

<hr>

**Changes in DungeonGenerator.cpp**

Then we gave the initial room new location when initiating it in Dungeon 

`URoom* root = NewObject<URoom>();`
`root->Init(def);`
`RoomList.Add(root);`
<hr>

`URoom* root = NewObject<URoom>();`
`FIntVector location = FIntVector(this->GetActorLocation());`
`root->Init(def, FIntVector(location.X / 375, location.Y / 375, location.Z /400));`
`RoomList.Add(root);`

<hr>

We had 2 different dungeon generator actors in the scene.
The first one spawned correctly in the correct position with all the rooms and what they contained here is picture what it looks like:
![image](https://user-images.githubusercontent.com/48365153/188839911-5c314e68-bb8e-4e72-bf13-5e575e49f627.png)


The second one spawned **only the room data that contains the collisions** for the doors and not any static meshes all anything else that was in the room map. And rooms spawned **in the map center position** (0,0,0) and not where the actor had been placed.

**Comment by BenPyton** [comment]
Hi Jalsson,

Is your second DungeonGenerator actor at the same place as the first one ?
Maybe the content of the rooms can't spawn due to overlapping with the rooms of the first dungeon...

Also, why do you need a second generator ? You should be careful if you don't want the two dungeons to overlap... 
There is no test of overlapping of a room with the rooms of another dungeon.

From what I remember from my code, the position member you set in the `URoom::Init` is overriden by the generation process (see `URoom::SetPositionFromDoor` for instance)

Maybe you should create a new member in `URoom` called `Offset` that you set in the `URoom::Init` instead of the position, and add it everywhere the `Position` member is used :)

Best regards.

**Comment by Jalsson** [comment]
Hi,

![image](https://user-images.githubusercontent.com/48365153/189122856-bcfe4301-59d2-4f29-94e8-39ca9f4e0fdf.png)

I managed to get the rooms to spawn in right spots and all the meshes to spawn in correctly when I **disabled tick for both** and **enabled it for the second one during the generation process**. 

But I still have the problem of the second dungeon generation not spawning in the first and last rooms. Do you have any idea why they are not spawning in? I checked that the **first room was not null here** when the room is init is called but it failed to initialize:

![image](https://user-images.githubusercontent.com/48365153/189123204-ef317160-89e5-49eb-90b8-005b49e8c626.png)


![image](https://user-images.githubusercontent.com/48365153/189122541-0141b8a1-5665-4b8c-a888-af1163680c3c.png)
**First room is missing**

![image](https://user-images.githubusercontent.com/48365153/189122634-62ac2d0b-8715-4eab-9f82-e58d03b3085a.png)
**Here is the first one where the stairs (First room) is visible** 

Thank you for the help!
BR.

**Comment by BenPyton** [comment]
Hi Jalsson,

I think I don't understand very well your issue...
I can see a room in your first screenshot, where you say it is missing.
I suppose it is the room with the stair that is missing, and another room takes its place...

Can I ask you why you are generating 2 dungeons at the same time? So I will be able to understand better the situation.

Is it possible to share with me a minimal project to reproduce your issue ?
If not, I will try in the next few days to reproduce your issue on my side, with the changes in code you provided earlier.

There is certainly something wrong in the plugin when there are multiple dungeon generators. As I said, I've never tested that before...
After your issue will be resolved, the plugin will be improved, for sure! :)

Best regards.

**Comment by Jalsson** [comment]
Hi BenPyton,

I must apologize that the angle of the picture is bad. I have added the stairs as the first room and it makes the dungeon have two floors. 

The room you are talking about spawned below and behind the stairs so I am 100% sure that the first room did not spawn in correctly.

The game is a multiplayer game and I have a landscape map where there are elevators that are used to teleport players to the dungeon. Each elevator is used to access a different dungeon. 

Unfortunately, I cannot share the project it's really big and I think it would be easier for you to just create a small project where dungeons are generated like 10 seconds apart. 

Thank you for your help!
Best Regards.

**Comment by BenPyton** [comment]
Hi Jalsson,

Of course You'll not share with me your project. I meant a minimal project you create on your side that is reproducing your issue accurately, so that it saves me a lot of time and I am sure to reproduce and fix your issue :)

If you don't have the time to provide me this minimal project, I will do it on my side, but since it is on my free time it will take some times for me to create this minimal project based on what I have understood of your issue, and it is not 100% sure to reproduce and fix your exact issue...

I will do the second one in the next few days if I have enough spare time :)

Best regards.

**Comment by BenPyton** [comment]
I have just though of something! 

There is indeed a global variable used by all the dungeons, in the UProceduralLevelStreaming there is the `UniqueLevelInstanceID` that is used to set a unique name for loaded room levels so that we can have multiple instances of the same room.
This static ID is reset to 0 in the `DungeonGenerator::CreateDungeon()`.

So the bug comes from here: the second generator tries to load the spawn room tha has the same name as the spawn room of the first generator, and the engine believe this level is already loaded and doesn't load it twice.

To fix your issue, you should create another static member along the `UniqueLevelInstanceID` where you store a `DungeonGenerator` ID.
You set this member to a unique number for each generator in the `CreateDungeon` where the level ID is reset to 0.

And finally, you add this ID in the level instance name in `ProceduralDungeonLevelStreaming::LoadLevelInstance_Internal()` where the `UniqueLevelPackageName` is set (line 151).

I didn't test it, so let me know if this resolves your issue :)

If this works, I will add it in the plugin, with the possibility to place the dungeon at the position of the generator too.

Best regards.

**Comment by Jalsson** [comment]
**Yes this was the exact problem!!!** 

I previously did try to change the `UniqueLevelInstanceID ` but I only tried to add like number 1 and 2 which did not yield any results. Here is the code I added

Added new public `UPROPERTY `to the `DungeonGenerator.h`

```
UPROPERTY(BlueprintReadWrite, Category = "Dungeon Generator")
int32 levelInstanceId;
```

Then assigned the new value in blueprints
![image](https://user-images.githubusercontent.com/48365153/189310454-2fda01d4-e14f-4384-837d-22a9415b097c.png)


Also added the **new static id** as you said dungeon in the `ProceduralLevelStreaming.h`

```
public:
	// Counter used by LoadLevelInstance to create unique level names
	static int32 UniqueLevelInstanceId;

	static int32 DungeonGeneratorId;
```
**`ProceduralLevelStreaming.cpp`**
```

int32 UProceduralLevelStreaming::UniqueLevelInstanceId = 0;
int32 UProceduralLevelStreaming::DungeonGeneratorId = 0;
```

And in the `ADungeonGenerator::CreateDungeon()` I gave the new variable to the `UProceduralLevelStreaming` object

```
void ADungeonGenerator::CreateDungeon()
{
	IsInit = false;
	NbInitRoom = 0;
	int TriesLeft = MaxTry;

	// generate level until there IsValidDungeon return true
	do {
		TriesLeft--;

		// Reset generation data
		UProceduralLevelStreaming::UniqueLevelInstanceId = 0;
		UProceduralLevelStreaming::DungeonGeneratorId = levelInstanceId;
```


And finally in **`ProceduralLevelStreaming.cpp`** line 151 added the new variable to the function

`UniqueLevelPackageName += TEXT("_LevelInstance_") + FString::FromInt((++UniqueLevelInstanceId)+ DungeonGeneratorId);`

**Comment by BenPyton** [comment]
For completion of this issue, I've released [the version 2.0.2 of the plugin](https://github.com/BenPyton/ProceduralDungeon/releases/tag/v2.0.2).\
It includes some code changes: 
- fix the multiple generator actors
- position offset of the dungeon using the generator actor location

I have not done them exactly like you did in this issue ticket.\
Feel free to keep your version, or use the new version, or only a part of its code, or get inspired by how I did it. :)

**Comment by NoeliusMax** [comment]
> Hi,
> 
> ![image](https://user-images.githubusercontent.com/48365153/189122856-bcfe4301-59d2-4f29-94e8-39ca9f4e0fdf.png)
> 
> I managed to get the rooms to spawn in right spots and all the meshes to spawn in correctly when I **disabled tick for both** and **enabled it for the second one during the generation process**.
> 
> But I still have the problem of the second dungeon generation not spawning in the first and last rooms. Do you have any idea why they are not spawning in? I checked that the **first room was not null here** when the room is init is called but it failed to initialize:
> 
> ![image](https://user-images.githubusercontent.com/48365153/189123204-ef317160-89e5-49eb-90b8-005b49e8c626.png)
> 
> ![image](https://user-images.githubusercontent.com/48365153/189122541-0141b8a1-5665-4b8c-a888-af1163680c3c.png) **First room is missing**
> 
> ![image](https://user-images.githubusercontent.com/48365153/189122634-62ac2d0b-8715-4eab-9f82-e58d03b3085a.png) **Here is the first one where the stairs (First room) is visible**
> 
> Thank you for the help! BR.

Hello guys!
I know this might not be the best place to ask, but could you tell me how to make all the rooms appear at the same height?
I'm new to Unreal and I'm trying to make a game with procedurally generated levels just with the same structure as the ones in Jalsson's images.
I've been trying but I can't get it right.
Sorry to bother you,
Best regards.

**Comment by BenPyton** [comment]
Hi NoeliusMax,

If you have any issue with the plugin, prefer creating a new issue ticket instead of necroing an old unrelated issue.

I don't understand well your issue...
If you want to have all the rooms on the same height (Z axis) then, juste create rooms with all the doors on the same height.
Your rooms can have different heights from each others, and the doors can be set at any height on each room, as long as all the doors in each room are on the same height.
This will ensure that your dungeon is in "2D" (all doors are of the dungeon are horizontally aligned).

For example: you can have a room of size (3,4,1) with all doors aligned on height 0; another room of size (5,5,10) also with doors on height 0; and another room of size (2,4,5) with all doors aligned on height 3.
With those rooms, your dungeon will be "flat" (all doors at the same height) but your rooms can have depth in positive height (like the second room) or negative height (like the third room).

If you can't spawn correctly a dungeon, then please first [read carefully the wiki from start to end](https://github.com/BenPyton/ProceduralDungeon/wiki/Dungeon-Generator), then [read this other issue](https://github.com/BenPyton/ProceduralDungeon/issues/10), and last create a new issue ticket with your explanations of what you want to do and what solutions you have tried.

Best regards.

**Comment by NoeliusMax** [comment]
Hi BenPyton, thanks a lot!
That was the solution I needed.
I'll be reading your wiki if I have any more problems.
Your plugin is amazing.
Thank you so much.
Best regards.
