### ISSUE TITLE
Spawning items to each level from blueprint results in overlapping/ duplicate items and incorrect spawns.

### ISSUE THREAD

**Issue by randopixel** [BenPyton/ProceduralDungeon#20]
I am unable to directly reference actors in instances of levels without referencing the same actors on all instances. 
An example with screen shots, I have a room (RoomA_Level) with16 spawn points available. In my blueprint, I directly reference the spawn points and populate an array. I then For Loop 7 times and during the loop i get a random array element and spawn at its transform, while both removing the spawn point from the array, then destroying it (attempts to make it unavailable to other instances). I also clear the array after the For loop. With a single room, this works. With multiple instances, all instances of RoomA treat all spawn points on the map as available, and I may get 4 or 5 chests in the same location on a few levels and not have enough chests on another, plus a random stack of chests from non-existent target points in the origin point of the start room.

![image](https://user-images.githubusercontent.com/117866486/217951014-0965988b-ec38-4478-a911-37ef0c6df8e5.png)

RoomA level blueprint 
![image](https://user-images.githubusercontent.com/117866486/217951248-6c89ab8d-cee6-4a07-9b99-6cd4fd976cb6.png)

Generator settings
![image](https://user-images.githubusercontent.com/117866486/217952932-ff92f4ff-3356-4699-8cc2-c32290299cc7.png)

Log errors on target points that dont exist and that I dont reference anywhere.
![image](https://user-images.githubusercontent.com/117866486/217954265-13fb3cbd-3b45-4f18-a25a-061db463c680.png)

Result in game:
https://youtu.be/BUF1wBb2S_k

Thank you for your time.

**Comment by BenPyton** [comment]
Hi @randopixel,
I'll take a look at it deeper when I have more time today or tomorrow.

However, for the error logs, I think it is caused because you destroy the spawn targets after using them, so the other rooms trying to spawn a chest on them can't (resulting in the chest spawning at (0,0,0) in the world).

However it seems weird to me that rooms references other rooms actors...

I have one crucial question for me to understand it well: Does the first room can spawn chests in the second one? Or another way to ask: do the chests can spawn in both rooms?

Best regards.

**Comment by randopixel** [comment]
What you saw was a dungeon of 15 instances of the same room. they use the room blueprint I have shown above. They all should have only spawned to their own room. All 15 instances have the same target points in them (instanced).

They should not spawn to the other instances at all. I need specific, per room spawn control.

Thanks again!

**Comment by BenPyton** [comment]
> They should not spawn to the other instances at all.

Yes I have understood that, but my specific question is:
- Is there chests spawning in other room instances? (not only the first room instanced)

For example, if you have this dungeon : 
```
[S]-[R]-[R]-[E]
 0   1   2   3  (room instance IDs)
```
and each room instance R should spawn 5 chests each (randomly or not)
Are there chests only in room ID 1? or can chests spawn also in room ID 2?

**Comment by randopixel** [comment]
I'm sorry. Yes, chests can and should spawn in every instance of the room. So in your dungeon, both R rooms would spawn 5 chests.
I should note that, when I removed the Destroy Actor, the chests stopped spawning at 0 0 0 starting room, and only the requested number of chests spawn in each room. So if I ask for 5, I get 5, they just often spawn in the same spot. Is it possible that I'm just misunderstanding how to remove possible spawn points and they are still being accessed by the room in the Random node? If that's the case, the problem wouldn't be with your generator at all.

**Comment by BenPyton** [comment]
What I ask is about the behaviour of the issue not what you expect 😓
In your issue, are chests spawning also in other room instances of the same room type? or are they spawn only in the first instance?
I clearly undestood what you would like 😅 
From the example I gave above, I understood you want room ID 1 to spawn 5 chests in its own spawn targets, and room ID 2 to spawn 5 chests on its own spawn targets.
And that actually, room 1 and 2 are spawning in each other targets.

What I ask you is if with your issue you have chests in room 2 as well as in room 1, or only in room 1.


Also, about your spawning code, I can suggest you some little things to improve it, and then we will check if it resolve your issue.
But first I need to ask you something else: Do you plan to use your spawn targets for other things than chests? or they will spawn only chests?
Then I can tell you what to do for your chest spawning code.

**Comment by randopixel** [comment]
I think I will only be spawning the chests. I will be using a separate set of target points in each room to do the same thing with traps.
I should be able to register the spawned chests into an array for loot distribution for each room, yes?

I definitely look forward to your code suggestions, as I think I may be misunderstanding how arrays work in blueprint.. it seems removing an item doesn't collapse the array so the slot is still accessible to the random? Not sure if that is right.

**Comment by BenPyton** [comment]
Ok so, first, you should move the chest spawning in the target points. For that, create a new function in your spawn target actor, as well as a boolean to check if the chest is already spawned on it:

![image](https://user-images.githubusercontent.com/13402355/218136084-76f3c365-705d-40cf-8289-b8ea0c81accb.png)

Then in the function, you do your spawn like in your screen code (the inside of your for loop) and setting to true the boolean:

![image](https://user-images.githubusercontent.com/13402355/218137157-8d77bd1e-a158-4734-9670-b61d3c2edd6d.png)

And in your room level blueprint, you create a function too and a variable array to store your target points actors:

![image](https://user-images.githubusercontent.com/13402355/218137905-12647a0b-8946-4387-892e-18d7bdbef5ec.png)

To set a variable as an array you click on the icon next to the variable type:

![image](https://user-images.githubusercontent.com/13402355/218138139-12b24faf-de8e-4cdb-930d-2d424f8470f6.png)

Be careful in blueprint, because nodes that does not have an exec pin does not cache their results. So the get random from the array you've done is **re-run for each connection** it has, and since the result is random for this node, the result is different for your remove from array, your transform used for spawning, and the destroyed called (hence the errors in your logs saying that actors is pending kill because you've destroyed another actor than the one you removed from the array).
So, to avoid that, in your room function, you can add a local variable which will store the random result in the for loop. 

![image](https://user-images.githubusercontent.com/13402355/218139398-586c447a-2a29-4f86-a8e3-6b861585bce5.png)

And finally the spawn logic now:

![image](https://user-images.githubusercontent.com/13402355/218142505-9c0b6530-b433-420d-9c7e-41889cfa5e34.png)

Be warned I didn't tested this code.

**Comment by randopixel** [comment]
Thank you so much for taking the extra time to educate.
much appreciated. I will close the report.
