### ISSUE TITLE
[HELP] Enhanced Input not working on MasterLevel, works on my other levels

### ISSUE THREAD

**Issue by Andipog** [BenPyton/ProceduralDungeon#34]
**Bug Description**
Enhanced Inputs don't work

**Technical information**
 - OS: Windows 11
 - Unreal: 5.2
 - Plugin Version: 2.1.2

**Steps To Reproduce**
Steps to reproduce the behaviour:
I think its a skill issue on my end

**Expected behaviour**
I want my character to be controlled by enhanced inputs, instead of the old ones, but idk if I have a choice

**Comment by BenPyton** [comment]
Hi @Andipog

This has nothing to do with the plugin. The plugin does not use anythingg related to any input system.  
The Enhanced Input system works fine on my end with the plugin.  
Make sure you set it up correctly. 

Take a look at [my example project](https://github.com/BenPyton/DungeonExample) I am currently making for the version 3.0.0 of the plugin.  
(you will not be able to use it yet if you don't compile yourself the 3.0.0 branch of the plugin, because I didn't released yet this precompiled version of the plugin)

Best regards.
