### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by MnkyArts** [BenPyton/ProceduralDungeon#40]
Hey, I understand this isn't exactly an issue, but I wasn't sure where else to express this.

I think it would be fantastic if there were a Discord server dedicated to this plugin. While there might be reasons for not having one yet, I believe it could significantly assist, especially new users, in getting started with the plugin. Additionally, it could serve as an excellent platform for sharing knowledge about the plugin and possibly even some related assets.

**Comment by BenPyton** [comment]
Hi @MnkyArts 

I understand what you mean, however, I don't know if there is a large enough community around this plugin to be really as active as you think... So I don't know if it's worth to manage a discord server on my free time in addition.

However, I saw the github "discussion" feature that could act as a place for anybody to discuss about the plugin.
I think maybe it would be better than a discord server because it will be embedded here in this repo like the wiki.
I've never used yet this feature though... 🤷 

Nevertheless, your idea would improve the interactivity of people about this plugin. 👍

Best regards.

**Comment by MnkyArts** [comment]
Hey @BenPyton, first thank you for your quick response!

In my personal experience, whenever I encounter difficulties with a plugin or open-source software, my first step is to check if there's a Discord server. Such a platform often has discussions where my question might have already been answered, or where members share their results and expertise. As someone who is relatively new to this field, I frequently face various challenges and errors, especially with this plugin (but that is really my fault! haha). Having a dedicated space to discuss these issues or to look up common problems would be incredibly helpful.

Additionally, I'm quite confident that the community behind this plugin is big enough to support an active Discord server. I've seen plugins and projects with far less activity on GitHub maintain lively and engaged Discord communities. I mean, even if its isn't extreamly big or active, it just would be an awesome place to get quick answers from the community or even find old topics of an encountered error.

Also i don't really think that such a Server needs that big of a management, im sure it would run pretty much on its own :)

Best regards.

**Comment by BenPyton** [comment]
First, thank you for your suggestion, because your helping me improving my plugin (even if its not the code directly, the user experience is also an important part).

I understand your point of view, and I agree with you that a dedicated place for people to discuss about the plugin would be a good addition.
I'm considering that for some times, but I don't know currently which one to choose between Discord and Github since they have both pros and cons...

- Discord Server: the discussions will have a better visibility among the people in the server, since discord is not only used for github content. So, questions will be more likely to have a quick response by somebody else than me.
- Github Discussion: this is integrated in the repo here, so I can manage all the stuff about the plugin in one place. Also I could convert easily discussions into issues and vice-versa. However, people willing to ask/answer questions or share ideas need to have a github account, and new discussions will certainly have less visibility than on discord.

Beside that, the main thing that refrain me to do that is I don't know if a plugin like this one can keep someone (other than me) engaged for a long time.
I think most people (if they actually download the plugin) will eventually give it a try before giving up, because there is too much work to do to have something functional (it's not just putting the plugin in your project and you have a result).
From the insights of the repo, only 1/5th of the repo visitors get to the wiki, and only half of them to the pages for implementing the dungeon generator.
And for those who are really trying to use it in their project, I think they are moving on from creating a game after a week or two, since it's actually a huge amount of work.
At the end, there is only few people actively using it for a long time, and currently I don't know if there is a published game using my plugin.

All that speech just to say that I think I will be the only one to actively answer people on either Discord or Github...
However, as you said it, maybe it would make the plugin easier to start with for newcomers, and will get better engagement.

Most of the time, I am deciding and prioritizing the improvements of the plugin when somebody actively asks it.
And since you just did that, then I'll give it a try soon. (just I'll still have to choose between Discord and Github)

Again, thank you for your feedback. People like you have been keeping this plugin alive for 4 years now.

**Comment by BenPyton** [comment]
Hi @MnkyArts 

So, I took a whole day to configure a simple server discord dedicated to the plugin.
I've put the invite links in the wiki for the people to join it.

I don't know if it people will be really engaged in a "community" around this plugin, as the server is empty for now (and I will can't be there 24h/24h to reply to anybody).
However, it's a test to give it a try. 🤷

Best regards.
