### ISSUE TITLE
[BUG] Unreal Engine 5.3 crashes on PIE when net mode is "Play As Client"

### ISSUE THREAD

**Issue by ervinasubartas** [BenPyton/ProceduralDungeon#53]
**Bug Description**
When I attempt to start a PIE instance whilst the net mode is set to "Play As Client", my engine crashes. This does not occur when the net mode is on standalone or server.

**Technical informations**
 - OS: Windows 11
 - Unreal: 5.3.2
 - Plugin Version: 3.2.2

**Steps To Reproduce**
1. Change Net Mode in multiplayer settings to "Play As Client".
2. Start a Play In Editor instance.

**Expected behavior**
Start a client-side instance of my game.

**Error**
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000478

UnrealEditor_ProceduralDungeon!ADungeonGenerator::UpdateRoomVisibility() [R:\ProceduralDungeon\Packaged\5.3\ProceduralDungeon\HostProject\Plugins\ProceduralDungeon\Source\ProceduralDungeon\Private\DungeonGenerator.cpp:402]
UnrealEditor_ProceduralDungeon!ADungeonGenerator::OnStateTick() [R:\ProceduralDungeon\Packaged\5.3\ProceduralDungeon\HostProject\Plugins\ProceduralDungeon\Source\ProceduralDungeon\Private\DungeonGenerator.cpp:546]

**Minimal repro project**
I received the same error in the Procedural Dungeon example project.

Other than this, the plugin is fantastic. Thank you!

**Comment by BenPyton** [comment]
Hi @ervinasubartas 

Thank you for your crash report.
I'll try to fix the code to avoid the crash.

However, when playing in multiplayer, you can't use a PIE instance, because the room level instances will have specific names for PIE and will mismatch with the non-PIE game instanced.
So the replication is not done correctly and lots of bugs are expected.
This is explained in [the wiki](https://github.com/BenPyton/ProceduralDungeon/wiki/Multiplayer#multiplayer-in-editor).

**Comment by BenPyton** [comment]
So the fix for this crash was simple and it will be included in a future version of the plugin
(see commit d13de7e) but other bugs or crashes can (*will*) appear later, and I won't be able to fix most of them, because they are inherent of how the Unreal Editor works.

Like I said in my previous comment, you can't test multiplayer directly in PIE (either in viewport or in a new window) because of how Unreal Engine handles level names **in editor**.
Then, if you want to play in editor, the `Net Mode` should always be standalone (not server nor client).
Or if you want to test multiplayer, you need to launch a standalone game instance (not a PIE), this will also have the benefit to reflect better how your game will run once packaged.

**Comment by ervinasubartas** [comment]
Whoops, sorry, I overlooked that in the docs. Either way, thank you very much - I'll use standalone game instances to test multiplayer instead of PIE from now on.

**Comment by BenPyton** [comment]
No problem :)
I think I will also update the wiki page to make it more visible, and to explain better why multiplayer in PIE can't work with the plugin.
