### ISSUE TITLE
[BUG]  GetAllDoors, Outdoors is a input. 

### ISSUE THREAD

**Issue by GamesAndBacon** [BenPyton/ProceduralDungeon#54]
![UnrealEditor_B9tjjN7jcR](https://github.com/BenPyton/ProceduralDungeon/assets/534830/3d4b4b4b-b555-446d-b681-e428e71563db)

The get all doors "OutDoors" is set as an input. 
using the most up to date version of the plugin on UE5.4

**Comment by BenPyton** [comment]
Hi @GamesAndBacon 

Yeah I know this is confusing for people that are not familiar with C++ but this is not a bug.
I made the mistake to put it as input because it is a common practice in C++ when working with arrays to put them as references in input of the functions. This way we avoid unnecessary copies and memory allocations.
So it was more natural to me to put the array as input when I made that node.

However, since it is confusing for most blueprint-only programmers, I will change that in the next major version of the plugin to put the array as output instead. It will however change nothing to the behavior of the node, it is already working as intended.

You use it by connecting the array you want to fill in the input, the array will be emptied and filled with the door actors.
If you really want it as output, you can slightly change the C++ code of the plugin by removing the `UPARAM(ref)` [here](https://github.com/BenPyton/ProceduralDungeon/blob/e4d09ac570e22611e659b17ae0d3373ad0b11e2d/Source/ProceduralDungeon/Public/Room.h#L118) so you have that instead:
```cpp
void GetAllDoors(TArray<ADoor*>& OutDoors) const;
```
Making it in fact as an output.

I will correct that only in the next major version of the plugin (v4.0.0) since this will break existing nodes. (see [semver](https://semver.org/#semantic-versioning-specification-semver) point 8)

**Comment by GamesAndBacon** [comment]
oh i seee, that does make sense. i understand why you have done it that way now. thank you for the reply
